notifications:
  email: false

dist: jessie
sudo: required

matrix:
  fast_finish: true

services:
  - postgresql
  - redis-server
  - docker

addons:
  postgresql: '9.4'

language: php

php: '7.0'
node_js: '6.1'

env:
  - SYMFONY_ENV=test

before_install:
  - sudo apt-get update -qq
install:
  # Remove error could not access file "$libdir/postgis-2.3": No such file or directory
  - sudo apt-get install -y $(apt-cache search postgis | awk '/^postgresql-9\.[2-6]-postgis-2.3/{printf " "$1}' )
  - sudo service postgresql restart

before_script:
  # Configure JSON Web Token
  - mkdir -p var/jwt
  - openssl genrsa -out var/jwt/private.pem 4096
  - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  # Configure PostgreSQL
  - psql -U postgres -c 'CREATE DATABASE coursiers_test;'
  - psql -U postgres -d coursiers_test -c 'CREATE EXTENSION postgis;'
  - psql -U postgres -d coursiers_test -c 'CREATE EXTENSION postgis_topology;'
  # Install PHP app
  - composer self-update
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --prefer-dist
  - php bin/console doctrine:schema:create --env=test
  # - psql -U postgres -d coursiers -f tests/AppBundle/Resources/sql/restaurants.sql > /dev/null
  - php bin/console server:start
  # Install JavaScript stuff
  # - npm install
  # - node_modules/.bin/webpack -p
  # # Install OSRM
  # - mkdir -p var/osrm
  # - wget https://s3.amazonaws.com/metro-extracts.mapzen.com/paris_france.osm.pbf -P var/osrm
  # - docker run -t -v $(pwd)/var/osrm:/data osrm/osrm-backend:v5.5.4 osrm-extract -p /opt/bicycle.lua /data/paris_france.osm.pbf
  # - docker run -t -v $(pwd)/var/osrm:/data osrm/osrm-backend:v5.5.4 osrm-contract /data/paris_france.osrm
  # - docker run -t -v $(pwd)/var/osrm:/data -d -p 5000:5000 osrm/osrm-backend:v5.5.4 osrm-routed /data/paris_france.osrm
script:
  # - curl 'http://localhost:5000/route/v1/bicycle/2.3706188,48.877821;2.385706,48.887031?overview=full'
  - cp phpunit.xml.dist phpunit.xml
  - phpunit
  - php vendor/bin/behat
