---
- name: Create redis.ini file
  become: yes
  copy: content="extension=redis.so" dest=/etc/php/7.0/mods-available/redis.ini

- name: Activate PHPRedis extension for CLI
  become: yes
  file:
    src: /etc/php/7.0/mods-available/redis.ini
    dest: /etc/php/7.0/cli/conf.d/20-redis.ini
    state: link

- name: Activate PHPRedis extension for PHP-FPM
  become: yes
  file:
    src: /etc/php/7.0/mods-available/redis.ini
    dest: /etc/php/7.0/fpm/conf.d/20-redis.ini
    state: link