api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix:   '/api'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

web:
    resource: '@AppBundle/Controller/'
    type:     'annotation'
    prefix:   /{_locale}

redirect_to_locale:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: false
