- hosts: all
  become: yes
  roles:
    - init
    - nginx
    - ANXS.postgresql
    - geerlingguy.php
    - DavidWittman.redis # Failed to reload sysctl: sysctl: permission denied on key 'vm.overcommit_memory
    - redis-tools
    - alexsegura.phpredis
    - phpredis-enable
    - nodejs
    - weareinteractive.pm2
