---
# - hosts: all
  # sudo:  true
  # vars:
  #   doc_root: /var/www/coursiers/web
  #   main_domain: coursiers.dev
  #   db_name: coursiers
  #   sys_packages:
  #     - mcrypt
  #     - vim
  #   php_packages:
  #     - { name: dev, package: php5-dev }
  #     - { name: pear, package: php-pear }
  #     - { name: xdebug, package: php5-xdebug }
  #     - { name: curl, package: php5-curl }
  #     - { name: mcrypt, package: php5-mcrypt }
  #     - { name: mysql, package: php5-mysql }
  #     - { name: pgsql, package: php5-pgsql }
  #   php_extensions: ~
  #   php_ppa: php5
  #   nodejs:
  #     version: 6.x
  #   redis_version: 3.2.1
  #   redis_bind: 127.0.0.1
  #   phpredis_version: develop
  # roles:
  #   - init
  #   # - php5-fpm
  #   # - php5-cli
  #   # - php5-common
  #   # - postgis
  #   - nginx
  #   # - DavidWittman.redis
  #   # - redis
  #   # - tersmitten.phpredis # Need some work to install latest
  #   - nodejs
  #   - weareinteractive.pm2

- hosts: vps
  become: yes
  become_method: su
  roles:
    # - init
    # - php5-fpm
    # - php5-cli
    # - php5-common
    # - nodejs
    # - postgis
    # - ANXS.postgresql
    # - nginx
    # - DavidWittman.redis # Failed to reload sysctl: sysctl: permission denied on key 'vm.overcommit_memory
    # - redis-tools
    - tersmitten.phpredis # Need some work to install latest
    # TODO enable redis PHP package
    - weareinteractive.pm2
